# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '发票信息', 'verbose_name_plural': '发票信息'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='buyer',
            field=models.CharField(blank=True, max_length=36, verbose_name='购买方名称'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='certification_no',
            field=models.CharField(blank=True, max_length=36, verbose_name='合格账号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='engine_no',
            field=models.CharField(blank=True, max_length=36, verbose_name='发动机号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='id_no',
            field=models.CharField(default='exit', max_length=36, verbose_name='身份证号码/组织机构代码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_ctime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开票日期'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='make_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='厂牌型号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='origin',
            field=models.CharField(blank=True, max_length=36, verbose_name='产地'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='retail_sales_units',
            field=models.CharField(blank=True, max_length=100, verbose_name='销货单位'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxpayer_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='纳税人识别码'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price_low',
            field=models.FloatField(default=0, verbose_name='价税合计小写'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_price_upper',
            field=models.CharField(blank=True, max_length=50, verbose_name='价税合计大写'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vehicletype',
            field=models.CharField(blank=True, max_length=36, verbose_name='车辆类型'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vin_no',
            field=models.CharField(blank=True, max_length=36, verbose_name='车架号'),
        ),
    ]
